# Generated by Django 4.1.4 on 2023-03-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='start_date',
            new_name='date',
        ),
    ]
