# Generated by Django 4.1.4 on 2023-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0012_alter_attendance_entrance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
