# Generated by Django 4.1.4 on 2023-02-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='adoption_date',
        ),
    ]
