# Generated by Django 4.1.4 on 2023-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=12)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_pass', models.CharField(max_length=12)),
                ('uaer_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
