# Generated by Django 4.1.4 on 2023-02-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0002_registeration_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='registeration',
            name='image',
            field=models.ImageField(upload_to='mysqlapp/images/'),
        ),
    ]
