# Generated by Django 4.1.4 on 2023-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0003_reg_alter_registeration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('Management', 'Management')], max_length=255),
        ),
    ]
