# Generated by Django 4.1.4 on 2023-03-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='db_image',
            field=models.BinaryField(editable=True, verbose_name='Image_db'),
        ),
        migrations.AlterField(
            model_name='images',
            name='django_image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
