# Generated by Django 4.1.4 on 2023-03-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_db', '0002_alter_images_db_image_alter_images_django_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='db_image',
            field=models.CharField(max_length=500),
        ),
    ]
