# Generated by Django 4.1.4 on 2023-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_db', '0003_alter_images_db_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='db_image',
            field=models.BinaryField(editable=True, verbose_name='Image_db'),
        ),
    ]
