# Generated by Django 4.1.4 on 2023-03-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_alter_attendance_date_alter_attendance_entrance_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
