# Generated by Django 4.1.4 on 2023-03-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0007_rename_start_date_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
