# Generated by Django 4.1.4 on 2023-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_alter_employee_picture_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], max_length=10),
        ),
    ]
