# Generated by Django 4.1.4 on 2023-03-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0010_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Absent', 'ABSENT'), ('Present', 'PRESENT')], max_length=10),
        ),
    ]
