# Generated by Django 4.1.4 on 2023-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0013_alter_attendance_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='db_picture',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Image_db'),
        ),
    ]
