# Generated by Django 4.1.4 on 2023-07-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0015_appuser_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='attendance_app.appuser'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
